/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWebhooksRouteImport } from './routes/_app.webhooks'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppInsumosRouteImport } from './routes/_app.insumos'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppFichasRouteImport } from './routes/_app.fichas'
import { Route as AppFechamentoRouteImport } from './routes/_app.fechamento'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppDemandaRouteImport } from './routes/_app.demanda'
import { Route as AppCardapioRouteImport } from './routes/_app.cardapio'
import { Route as ApiWebhooksN8nRouteImport } from './routes/api.webhooks.n8n'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppInsumosRoute = AppInsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFichasRoute = AppFichasRouteImport.update({
  id: '/fichas',
  path: '/fichas',
  getParentRoute: () => AppRoute,
} as any)
const AppFechamentoRoute = AppFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandaRoute = AppDemandaRouteImport.update({
  id: '/demanda',
  path: '/demanda',
  getParentRoute: () => AppRoute,
} as any)
const AppCardapioRoute = AppCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksN8nRoute = ApiWebhooksN8nRouteImport.update({
  id: '/api/webhooks/n8n',
  path: '/api/webhooks/n8n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/cardapio': typeof AppCardapioRoute
  '/demanda': typeof AppDemandaRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fichas': typeof AppFichasRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/insumos': typeof AppInsumosRoute
  '/producao': typeof AppProducaoRoute
  '/webhooks': typeof AppWebhooksRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cardapio': typeof AppCardapioRoute
  '/demanda': typeof AppDemandaRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fichas': typeof AppFichasRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/insumos': typeof AppInsumosRoute
  '/producao': typeof AppProducaoRoute
  '/webhooks': typeof AppWebhooksRoute
  '/': typeof AppIndexRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/cardapio': typeof AppCardapioRoute
  '/_app/demanda': typeof AppDemandaRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/fechamento': typeof AppFechamentoRoute
  '/_app/fichas': typeof AppFichasRoute
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/insumos': typeof AppInsumosRoute
  '/_app/producao': typeof AppProducaoRoute
  '/_app/webhooks': typeof AppWebhooksRoute
  '/_app/': typeof AppIndexRoute
  '/api/webhooks/n8n': typeof ApiWebhooksN8nRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cardapio'
    | '/demanda'
    | '/equipe'
    | '/estoque'
    | '/fechamento'
    | '/fichas'
    | '/fornecedores'
    | '/insumos'
    | '/producao'
    | '/webhooks'
    | '/api/webhooks/n8n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cardapio'
    | '/demanda'
    | '/equipe'
    | '/estoque'
    | '/fechamento'
    | '/fichas'
    | '/fornecedores'
    | '/insumos'
    | '/producao'
    | '/webhooks'
    | '/'
    | '/api/webhooks/n8n'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/cardapio'
    | '/_app/demanda'
    | '/_app/equipe'
    | '/_app/estoque'
    | '/_app/fechamento'
    | '/_app/fichas'
    | '/_app/fornecedores'
    | '/_app/insumos'
    | '/_app/producao'
    | '/_app/webhooks'
    | '/_app/'
    | '/api/webhooks/n8n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWebhooksN8nRoute: typeof ApiWebhooksN8nRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insumos': {
      id: '/_app/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof AppInsumosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fichas': {
      id: '/_app/fichas'
      path: '/fichas'
      fullPath: '/fichas'
      preLoaderRoute: typeof AppFichasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fechamento': {
      id: '/_app/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AppFechamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demanda': {
      id: '/_app/demanda'
      path: '/demanda'
      fullPath: '/demanda'
      preLoaderRoute: typeof AppDemandaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cardapio': {
      id: '/_app/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof AppCardapioRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/n8n': {
      id: '/api/webhooks/n8n'
      path: '/api/webhooks/n8n'
      fullPath: '/api/webhooks/n8n'
      preLoaderRoute: typeof ApiWebhooksN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCardapioRoute: typeof AppCardapioRoute
  AppDemandaRoute: typeof AppDemandaRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFechamentoRoute: typeof AppFechamentoRoute
  AppFichasRoute: typeof AppFichasRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppInsumosRoute: typeof AppInsumosRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCardapioRoute: AppCardapioRoute,
  AppDemandaRoute: AppDemandaRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFechamentoRoute: AppFechamentoRoute,
  AppFichasRoute: AppFichasRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppInsumosRoute: AppInsumosRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWebhooksN8nRoute: ApiWebhooksN8nRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
